# Site settings
title: Vladimir Iglovikov blog
email:
#description: "Musings of a Computer Scientist."
baseurl: ""
url: "http://ternaus.github.io"

twitter_username: viglovikov
github_username:  ternaus
linkedin_username: iglovikov

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

theme: jekyll-theme-cayman