# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Ternaus Blog"

name: "Vladimir Iglovikov"

description: "Free format blog of Vladimir Iglovikov"

repository: "ternaus/ternaus.github.io"

teaser: /assets/images/teaser.jpg

breadcrumbs: true  # disabled by default

yandex_site_verification: "45b0fcdd4b98ee41"

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: ternausX

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-83593675-1

baseurl: "" # the subpath of your site, e.g. /blog
url: "ternaus.blog" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: viglovikov
github_username:  ternaus
linkedin_username: iglovikov

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.20.1"
#minimal_mistakes_skin: "air"
#theme: minima

plugins:
  - jekyll-feed
  - jekyll-include-cache

disable_disk_cache: True

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      words_per_minute: 250
      comments: true
      share: false
      related: true
      show_date: true
      author_profile: true
  - scope:
      path: ""
      type: tag
    values:
      author_profile: true
  - scope:
      path: ""
      type: category
    values:
      comments: false

comments:
  provider: "utterances"
  utterances:
    theme: "github-light" # "github-dark"
    issue_term: "pathname"

search: true

google:
  search_engine_id: 012651648844144704873:_8__ljh324a

#facebook:
#  app_id:  779888532817216

twitter:
  username: "viglovikov"

og_image: /assets/images/teaser.jpg

atom_feed:
  path: "http://feeds.feedburner.com/TernausBlog"

#social:
#  type:  Person
#  links:
#    - "https://twitter.com/viglovikov"
#    - "https://www.linkedin.com/in/iglovikov"

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-83593675-1"
    anonymize_ip: false # default

author:
  name     : "Vladimir Iglovikov"
  avatar   : "/assets/images/candidate.jpg"
  bio      : "PhD in Physics. Veteran of Russian Spetsnaz. Kaggle Grandmaster."
  links:
    - label: "Twitter"
      icon: "fab fa-twitter-square"
      url: "https://twitter.com/viglovikov"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/iglovikov/"
    - label: "Kaggle"
      icon: "fab fa-kaggle"
      url: "https://www.kaggle.com/iglovikov"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/ternaus"
    - label: "Google Scholar"
      icon: "fas fa-user-graduate"
      url: "https://scholar.google.com/citations?user=vkjh9X0AAAAJ&hl=en#"

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

compress_html:
  clippings: all
  ignore:
    envs: development  # disable compression in dev environment


paginate: 10

exclude:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
   - .idea/
